.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH DamnVid 1 "2010-05-24" "" "Linux User's Manual"

.SH NAME
DamnVid \- Program for downloading and converting videos

..SH SYNOPSIS
.B damnvid
.RI "[OPTIONS] video1 video2 ... module1.module.damnvid module2.module.damnvid ..."
.br

.SH DESCRIPTION
\fBDamnVid\fP is an application to download and convert videos from your hard drive or from dozens of video sharing websites like YouTube, Dailymotion, Veoh, Metacafe, etc. Basically, it's a video downloader and converter that sucks less.
From the command line, you can specify the path of local video files to add to \fBDamnVid\fP's video list, or the path of DamnVid modules (*.module.damnvid) to install them.

.SH OPTIONS
.IP \fB\-q\fP
Quiet mode.
.IP \fB\--config=CONFIGDIR\fP
Stores configuration in CONFIGDIR (default: $HOME/.damnvid)
.IP \fB\--myvideos=VIDEOSDIR\fP
Treats VIDEOSDIR as your Videos folder (default: $HOME/Videos)
.IP \fB\--temp=TMPDIR\fP
Stores temporary files in TMPDIR (default: CONFIGDIR/temp)
.IP \fB\--flush\fP
Forces Python to run unbuffered (use this if the log gets truncated).
.IP \fB\--dump-locale-warnings\fP
Creates a log file of strings that haven't been translated.

.SH BUGS
Please report bugs using the application's built-in "Report a bug" feature, or on the DamnVid bug tracker at
.RB < http://code.google.com/p/damnvid/issues/list >.

.SH "SEE ALSO"
ffmpeg(1)
