.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH DamnVid 1 "2010-05-24" "" "Linux User's Manual"

.SH NAME
DamnVid \- program for downloading and converting online videos

..SH SYNOPSIS
.B damnvid
.RI [ --config ] [ --rebuild-modules ] [ --flush ] [ -q ] [ --dump-locale-warnings ]
.br

.SH DESCRIPTION
This manual page explains the \fBDamnVid\fP program. The \fBDamnVid\fP is an application to download and convert videos from your hard drive or from dozens of video sharing websites like YouTube, Dailymotion, Veoh, Metacafe, etc. Basically, it's a video downloader and converter that sucks less. 

DamnVid is written in python and is cross-platform. DamnVid make use of the FFmpeg library to do it's magic

.SH OPTIONS
.IP \fB\-q\fP
Quiet mode
.IP \fB\--config\fP
Use alternate config file
.IP \fB\--rebuild-modules\fP
Force rebuilding of all modules
.IP \fB\--flush\fP
???
.IP \fB\--dump-locale-warnings\fP
???

.SH NOTES

.SH "SEE ALSO"
ffmpeg(1)