# -*- coding: utf-8 -*-
from dUI import *
from dLog import *
from dTubes import *
import dSysInfo
class DamnReportBug(wx.Dialog):
	def __init__(self, parent, id, main):
		Damnlog('Opening bug report form.')
		self.parent = main
		wx.Dialog.__init__(self, parent, id, DV.l('Report a bug'))
		Damnlog('Building UI of bug dialog.')
		topvbox = wx.BoxSizer(wx.VERTICAL)
		self.SetSizer(topvbox)
		panel = wx.Panel(self, -1)
		panelvbox = wx.BoxSizer(wx.VERTICAL)
		topvbox.Add(panel, 1, wx.EXPAND)
		panel.SetSizer(panelvbox)
		panelvbox.Add((0, DV.border_padding))
		panelhbox = wx.BoxSizer(wx.HORIZONTAL)
		panelvbox.Add(panelhbox)
		panelvbox.Add((0, DV.border_padding))
		panelhbox.Add((DV.border_padding, 0))
		panelbox = wx.BoxSizer(wx.VERTICAL)
		panelhbox.Add(panelbox)
		panelhbox.Add((DV.border_padding, 0))
		formtitle = wx.StaticText(panel, -1, DV.l('Report a bug'))
		formtitle.SetFont(wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD))
		panelbox.Add(formtitle)
		panelbox.Add(wx.StaticText(panel, -1, DV.l('Thanks for taking the time to report a bug.')))
		panelbox.Add((0, DV.border_padding*2))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('Before reporting a bug, please make sure to check for updates:')))
		panelbox.Add((0, DV.border_padding))
		checkupdates = wx.Button(panel, -1, DV.l('Check for updates'))
		self.Bind(wx.EVT_BUTTON, self.parent.onCheckUpdates, checkupdates)
		panelbox.Add(checkupdates, 0, wx.ALIGN_CENTER)
		panelbox.Add((0, DV.border_padding*2))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('Please fill the form below to complete your bug report.')))
		panelbox.Add((0, DV.border_padding))
		panelbox.Add(wx.StaticLine(self, -1))
		panelbox.Add((0, DV.border_padding))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('Short description of the problem:')))
		self.description = wx.TextCtrl(panel, -1)
		panelbox.Add(self.description, 0, wx.EXPAND)
		panelbox.Add((0, 2 * DV.border_padding))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('What steps did you take for the problem to happen?')))
		self.steps = wx.TextCtrl(panel, -1, value='1. \n2. \n3. ', style=wx.TE_MULTILINE)
		panelbox.Add(self.steps, 0, wx.EXPAND)
		panelbox.Add(wx.StaticText(panel, -1, DV.l('(If you tried to download a video, please include its URL.)')))
		panelbox.Add((0, 2 * DV.border_padding))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('System information:')))
		sysinfo = dSysInfo.DamnSysinfo()
		if sysinfo != u'System information collection failed.':
			sysinfo = u'-- Auto-collected system information --\n' + sysinfo + u'\n-- End of auto-collected system information --'
		self.sysinfo = wx.TextCtrl(panel, -1, value=sysinfo, style=wx.TE_MULTILINE)
		panelbox.Add(self.sysinfo, 0, wx.EXPAND)
		panelbox.Add((0, 2 * DV.border_padding))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('Email-address (Optional):')))
		self.email = wx.TextCtrl(panel, -1)
		panelbox.Add(self.email, 0, wx.EXPAND)
		panelbox.Add(wx.StaticText(panel, -1, DV.l('(You will be notified at this address when there is progress about this bug.)')))
		panelbox.Add((0, 2 * DV.border_padding))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('In addition to this information, DamnVid\'s log file will also be sent.')))
		panelbox.Add(wx.StaticText(panel, -1, DV.l('This file is located here: ') + DamnUnicode(DV.log_file)))
		panelbox.Add((0, 2 * DV.border_padding))
		buttonsizer = wx.BoxSizer(wx.HORIZONTAL)
		panelbox.Add(buttonsizer, 0, wx.ALIGN_RIGHT)
		self.loading = wx.animate.GIFAnimationCtrl(panel, -1, DV.images_path + 'bugreportload.gif')
		self.send = wx.Button(panel, -1, DV.l('Send'))
		self.Bind(wx.EVT_BUTTON, self.onSend, self.send)
		buttonsizer.Add(self.loading)
		buttonsizer.Add(self.send)
		self.loading.Hide()
		buttonsizer.Add((DV.border_padding, 0))
		closebutton = wx.Button(panel, -1, DV.l('Cancel'))
		self.Bind(wx.EVT_BUTTON, self.onCancel, closebutton)
		buttonsizer.Add(closebutton)
		self.Bind(DV.evt_bugreport, self.onReportUpdate)
		Damnlog('UI built, centering report bug dialog.')
		self.SetClientSize(panel.GetBestSize())
		self.Center()
		Damnlog('Report bug dialog ready to be shown.')
	def onCancel(self, event=None):
		self.Close(True)
	def onReportUpdate(self, event):
		info = event.GetInfo()
		Damnlog('Bug report update event fired with info:', info)
		self.send.Show()
		self.loading.Stop()
		self.loading.Hide()
		self.Layout()
		if info['error']:
			icon = wx.ICON_ERROR
		else:
			icon = wx.ICON_INFORMATION
		dlg = wx.MessageDialog(None, info['dialog'], info['title'], wx.OK | icon)
		dlg.SetIcon(DV.icon)
		dlg.ShowModal()
		dlg.Destroy()
		if info['closedialog']:
			Damnlog('Closing bug report dialog as requested by event,')
			self.onCancel()
	def onSend(self, event):
		Damnlog('Send bug report button clicked.')
		self.send.Hide()
		self.loading.Show()
		self.loading.Play()
		self.Layout()
		desc = DamnUnicode(self.description.GetValue())
		email = DamnUnicode(self.email.GetValue())
		sysinfo = DamnUnicode(self.sysinfo.GetValue())
		steps = DamnUnicode(self.steps.GetValue())
		Damnlog('Spawning DamnBugReporter with information: \n\tDescription: ' + desc + u'\n\tSystem info: ' + sysinfo + '\n\tSteps:\n' + steps + u'\n\tEmail: ', email)
		DamnBugReporter(desc, steps, sysinfo, email, parent=self).start()
		Damnlog('DamnBugReporter spawned and launched.')
